name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - book

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
          
      - name: apt install
        run: |
          sudo apt update -y
          sudo apt install -y $(cat pkglist.txt)
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
          
      - name: set LANG
        run: sh lang-zh.sh	 
        
      - name: Git Config
        run: git config user.name whitewum && git config user.email min.wu@vesoft.com

      - name: show git branch
        run: | 
          git branch
      - name: mk and Compress
        run: |
           mkdocs build
           ls -altr
           tar -czf book.tar.gz site/pdf/NebulaGraph-CN.pdf
           
      - name: Transfer
        # uses: garygrossgarten/github-action-scp@release
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.port }}
          source: book.tar.gz
          target: /usr/web

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /usr/web/nebula-docs/
            tar -xzf /usr/web/book.tar.gz -C /usr/web/nebula-docs/
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
<<<<<<< HEAD
      #     publish_dir: ./site
<<<<<<< HEAD
>>>>>>> 3bc82431 (Update deploy.yaml)
=======
>>>>>>> d49fbb9c (fix deploy.yaml)
=======
      #     publish_dir: ./site
>>>>>>> 86b47a80 (rebase master)
